services:
  nginx:
    image: nginx:alpine
    container_name: ment-creator-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/audio_files:/app/audio_files
    depends_on:
      - frontend
      - backend
    networks:
      - ment-creator-network

  frontend:
    build:
      context: ./frontend/ment-gen
      dockerfile: Dockerfile
    container_name: ment-creator-frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://3.35.10.208/api/v1
    depends_on:
      - backend
    networks:
      - ment-creator-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ment-creator-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY}
      - PROJECT_NAME=${PROJECT_NAME:-ARS TTS System}
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - FIRST_SUPERUSER=${FIRST_SUPERUSER:-admin@example.com}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD:-changethis}
    volumes:
      - ./backend/audio_files:/app/audio_files
      - ./backend/voice_samples:/app/voice_samples
      - ./backend/voice_models:/app/voice_models
      - ./backend/temp_processing:/app/temp_processing
    depends_on:
      - db
    networks:
      - ment-creator-network

  db:
    image: postgres:17
    container_name: ment-creator-db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    networks:
      - ment-creator-network
volumes:
  app-db-data:

networks:
  ment-creator-network:
    driver: bridge
