services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

