services:
  redis:
    image: redis:latest
    container_name: redis_cont
    restart: always
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redisinsight:/data

volumes:
  redisinsight:

