"""deleted voice actor models

Revision ID: 0cc81e9f6eb0
Revises: 0064f815f443
Create Date: 2025-06-08 21:53:24.200251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cc81e9f6eb0'
down_revision: Union[str, None] = '0064f815f443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 순서 중요: 외래키 제약조건 먼저 삭제, 그 다음 컬럼 삭제, 마지막에 테이블 삭제
    op.drop_constraint(op.f('ttsgeneration_voice_model_id_fkey'), 'ttsgeneration', type_='foreignkey')
    op.drop_column('ttsgeneration', 'voice_model_id')
    op.drop_table('voicemodel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ttsgeneration', sa.Column('voice_model_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('ttsgeneration_voice_model_id_fkey'), 'ttsgeneration', 'voicemodel', ['voice_model_id'], ['id'])
    op.create_table('voicemodel',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('model_version', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('training_data_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('TRAINING', 'READY', 'ERROR', 'DEPRECATED', name='modelstatus'), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('voice_actor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('model_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['voice_actor_id'], ['voiceactor.id'], name=op.f('voicemodel_voice_actor_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('voicemodel_pkey'))
    )
    # ### end Alembic commands ###
