"""Fix foreign key relationships

Revision ID: 772cc1d17f77
Revises: cf5e06ba3710
Create Date: 2025-06-03 20:49:36.266814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '772cc1d17f77'
down_revision: Union[str, None] = 'cf5e06ba3710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
