"""Add source_handle and target_handle to ScenarioConnection

Revision ID: 797199376b8e
Revises: 98a64ae4170c
Create Date: 2025-07-06 16:17:20.920531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797199376b8e'
down_revision: Union[str, None] = '98a64ae4170c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
