"""add a field of file_path

Revision ID: 897c6edf51f9
Revises: cb04883a274c
Create Date: 2025-02-23 17:01:37.278052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '897c6edf51f9'
down_revision: Union[str, None] = 'cb04883a274c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ment', sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ment', 'file_path')
    # ### end Alembic commands ###
