"""enhance scenario nodes with ARS support

Revision ID: b8ba2777a1e4
Revises: 0cc81e9f6eb0
Create Date: 2025-06-29 19:01:49.292374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8ba2777a1e4'
down_revision: Union[str, None] = '0cc81e9f6eb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables in correct order (dependent tables first)
    op.drop_table('deploymentapproval')
    op.drop_table('deploymenthistory')
    op.drop_table('approvalrecord')
    op.drop_table('deployment')
    op.drop_column('scenario', 'deployed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenario', sa.Column('deployed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table('approvalrecord',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('deployment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('step_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('step_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('required_role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], name=op.f('approvalrecord_approved_by_fkey')),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], name=op.f('approvalrecord_deployment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('approvalrecord_pkey'))
    )
    op.create_table('deploymenthistory',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deployment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('deployment_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('performed_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('performed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], name=op.f('deploymenthistory_deployment_id_fkey')),
    sa.ForeignKeyConstraint(['performed_by'], ['user.id'], name=op.f('deploymenthistory_performed_by_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deploymenthistory_pkey'))
    )
    op.create_table('deployment',
    sa.Column('environment', postgresql.ENUM('DEVELOPMENT', 'STAGING', 'PRODUCTION', name='deploymentenvironment'), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('rollback_version', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('scenario_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'DEPLOYING', 'DEPLOYED', 'FAILED', 'ROLLED_BACK', name='deploymentstatus'), autoincrement=False, nullable=False),
    sa.Column('deployed_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['deployed_by'], ['user.id'], name='deployment_deployed_by_fkey'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario.id'], name='deployment_scenario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='deployment_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('deploymentapproval',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deployment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('required_role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], name=op.f('deploymentapproval_approved_by_fkey')),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], name=op.f('deploymentapproval_deployment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deploymentapproval_pkey'))
    )
    # ### end Alembic commands ###
